function thermalModel = prepareSimscapeModelInputs_v2(param)
    % ######## PREPARE SIMSCAPE simpleThermalModel MODEL ########
    thermalModel.mdl = "simpleThermalModel_v2";

    % Use a SimulationInput object to configure the model for our simulation.
    thermalModel.sim.in = Simulink.SimulationInput(thermalModel.mdl);

    % Solver setttings
    thermalModel.sim.in = thermalModel.sim.in.setModelParameter(...
        SolverType="Variable-step",...
        SolverName="VariableStepAuto",...
        RelTol="1e-6",...
        AbsTol="1e-7",...
        StopTime=string(param.orb.durationHours*3600));
    
    
    % Define thermal resistance inputs
    blk_RXplus = thermalModel.mdl + "/RX+";
    blk_RXminus = thermalModel.mdl + "/RX-";
    blk_RYplus = thermalModel.mdl + "/RY+";
    blk_RYminus = thermalModel.mdl + "/RY-";
    blk_RZplus = thermalModel.mdl + "/RZ+";
    blk_RZminus = thermalModel.mdl + "/RZ-";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...
    blk_RXplus, "resistance", string(param.resistance(1)),...
    blk_RXminus, "resistance", string(param.resistance(2)),...
    blk_RYplus, "resistance", string(param.resistance(3)),...
    blk_RYminus, "resistance", string(param.resistance(4)),...
    blk_RZplus, "resistance", string(param.resistance(5)),...
    blk_RZminus, "resistance", string(param.resistance(6)));

    %% Define inputs for the Internal Node 1
    blk_thermalMass = thermalModel.mdl + "/Internal Node/Internal Node 1";
    blk_internalNodePwr = thermalModel.mdl + "/Internal Node/Internal Node Pwr";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...
    blk_thermalMass, "mass", string(param.internalNodeMass(1)),...
    blk_thermalMass, "sp_heat", string(param.internalNodeCp(1)),...
    blk_internalNodePwr, "VariableName", 'param.thermal.internalPwr');


    %% Define inputs for Face X+ block
    faceId = 1;

    % Main
    blk_RadBlanket = thermalModel.mdl + "/Face X+/RadHeatBlanket";
    blk_Rblanket = thermalModel.mdl + "/Face X+/R_Blanket";
    blk_thermalMass = thermalModel.mdl + "/Face X+/Thermal Mass";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(... 
        blk_RadBlanket, "area", string(param.facesArea(faceId)),...
        blk_RadBlanket, "rad_tr_coeff", string(param.kradFace2Blanket(faceId)),...
        blk_Rblanket, "resistance", string(param.resistanceBlanket(faceId)),...
        blk_thermalMass, "mass", string(param.facesMass(faceId)),...
        blk_thermalMass, "sp_heat", string(param.facesCp(faceId)));

    % Enviromental Block
    blk_solarFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment X+/Solar Flux";
    blk_IRFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment X+/IR Flux";
    blk_AlbedoFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment X+/Albedo Flux";
    
    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_solarFlux, "VariableName", 'param.thermal.faceSolar.Xplus',...
        blk_IRFlux, "VariableName", 'param.thermal.faceIR.Xplus',...
        blk_AlbedoFlux, "VariableName",'param.thermal.faceAlbedo.Xplus');

    % Neighboor Faces Sub-block
    blk_RXplusYplus = thermalModel.mdl + "/Face X+/RX+Y+";
    blk_RXplusYminus = thermalModel.mdl + "/Face X+/RX+Y-";
    blk_RXplusZplus = thermalModel.mdl + "/Face X+/RX+Z+";
    blk_RXplusZminus = thermalModel.mdl + "/Face X+/RX+Z-";
    blk_RBXplusYplus = thermalModel.mdl + "/Face X+/RBX+Y+";
    blk_RBXplusYminus = thermalModel.mdl + "/Face X+/RBX+Y-";
    blk_RBXplusZplus = thermalModel.mdl + "/Face X+/RBX+Z+";
    blk_RBXplusZminus = thermalModel.mdl + "/Face X+/RBX+Z-";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...
        blk_RXplusYplus, "resistance", string(param.resistanceInterFaces(faceId, 3)),...
        blk_RXplusYminus, "resistance", string(param.resistanceInterFaces(faceId, 4)),...
        blk_RXplusZplus, "resistance", string(param.resistanceInterFaces(faceId, 5)),...
        blk_RXplusZminus, "resistance", string(param.resistanceInterFaces(faceId, 6)), ...
        blk_RBXplusYplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 3)),...
        blk_RBXplusYminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 4)),...
        blk_RBXplusZplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 5)),...
        blk_RBXplusZminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 6)));

    % OuterLayer Sub-block
    blk_radiativeHeatTransfer = thermalModel.mdl + "/Face X+/OuterLayer/Radiative Heat Transfer";
    blk_thermalMassBlanket = thermalModel.mdl + "/Face X+/OuterLayer/Thermal Mass Blanket";


    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_radiativeHeatTransfer, "area", string(param.facesArea(faceId)),...
        blk_radiativeHeatTransfer, "rad_tr_coeff", string(param.krad(faceId)),...
        blk_thermalMassBlanket, "mass", string(param.facesBlanketMass(faceId)),...
        blk_thermalMassBlanket, "sp_heat", string(param.facesBlanketCp(faceId)));

    %% Define inputs for Face X- block
    faceId = 2;

    % Main
    blk_RadBlanket = thermalModel.mdl + "/Face X-/RadHeatBlanket";
    blk_Rblanket = thermalModel.mdl + "/Face X-/R_Blanket";
    blk_thermalMass = thermalModel.mdl + "/Face X-/Thermal Mass";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(... 
        blk_RadBlanket, "area", string(param.facesArea(faceId)),...
        blk_RadBlanket, "rad_tr_coeff", string(param.kradFace2Blanket(faceId)),...
        blk_Rblanket, "resistance", string(param.resistanceBlanket(faceId)),...
        blk_thermalMass, "mass", string(param.facesMass(faceId)),...
        blk_thermalMass, "sp_heat", string(param.facesCp(faceId)));

    % Enviromental Block
    blk_solarFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment X-/Solar Flux";
    blk_IRFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment X-/IR Flux";
    blk_AlbedoFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment X-/Albedo Flux";
    
    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_solarFlux, "VariableName", 'param.thermal.faceSolar.Xminus',...
        blk_IRFlux, "VariableName", 'param.thermal.faceIR.Xminus',...
        blk_AlbedoFlux, "VariableName",'param.thermal.faceAlbedo.Xminus');

    % Neighboor Faces Sub-block
    blk_RXminusYplus = thermalModel.mdl + "/Face X-/RX-Y+";
    blk_RXminusYminus = thermalModel.mdl + "/Face X-/RX-Y-";
    blk_RXminusZplus = thermalModel.mdl + "/Face X-/RX-Z+";
    blk_RXminusZminus = thermalModel.mdl + "/Face X-/RX-Z-";
    blk_RBXminusYplus = thermalModel.mdl + "/Face X-/RBX-Y+";
    blk_RBXminusYminus = thermalModel.mdl + "/Face X-/RBX-Y-";
    blk_RBXminusZplus = thermalModel.mdl + "/Face X-/RBX-Z+";
    blk_RBXminusZminus = thermalModel.mdl + "/Face X-/RBX-Z-";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...
        blk_RXminusYplus, "resistance", string(param.resistanceInterFaces(faceId, 3)),...
        blk_RXminusYminus, "resistance", string(param.resistanceInterFaces(faceId, 4)),...
        blk_RXminusZplus, "resistance", string(param.resistanceInterFaces(faceId, 5)),...
        blk_RXminusZminus, "resistance", string(param.resistanceInterFaces(faceId, 6)),...
        blk_RBXminusYplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 3)),...
        blk_RBXminusYminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 4)),...
        blk_RBXminusZplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 5)),...
        blk_RBXminusZminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 6)));

    % OuterLayer Sub-block
    blk_radiativeHeatTransfer = thermalModel.mdl + "/Face X-/OuterLayer/Radiative Heat Transfer";
    blk_thermalMassBlanket = thermalModel.mdl + "/Face X-/OuterLayer/Thermal Mass Blanket";


    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_radiativeHeatTransfer, "area", string(param.facesArea(faceId)),...
        blk_radiativeHeatTransfer, "rad_tr_coeff", string(param.krad(faceId)),...
        blk_thermalMassBlanket, "mass", string(param.facesBlanketMass(faceId)),...
        blk_thermalMassBlanket, "sp_heat", string(param.facesBlanketCp(faceId)));

    %% Define inputs for Face Y+ block
    faceId = 3;

    % Main
    blk_RadBlanket = thermalModel.mdl + "/Face Y+/RadHeatBlanket";
    blk_Rblanket = thermalModel.mdl + "/Face Y+/R_Blanket";
    blk_thermalMass = thermalModel.mdl + "/Face Y+/Thermal Mass";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(... 
        blk_RadBlanket, "area", string(param.facesArea(faceId)),...
        blk_RadBlanket, "rad_tr_coeff", string(param.kradFace2Blanket(faceId)),...
        blk_Rblanket, "resistance", string(param.resistanceBlanket(faceId)),...
        blk_thermalMass, "mass", string(param.facesMass(faceId)),...
        blk_thermalMass, "sp_heat", string(param.facesCp(faceId)));

    % Enviromental Block
    blk_solarFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Y+/Solar Flux";
    blk_IRFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Y+/IR Flux";
    blk_AlbedoFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Y+/Albedo Flux";
    
    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_solarFlux, "VariableName", 'param.thermal.faceSolar.Yplus',...
        blk_IRFlux, "VariableName", 'param.thermal.faceIR.Yplus',...
        blk_AlbedoFlux, "VariableName",'param.thermal.faceAlbedo.Yplus');

    % Neighboor Faces Sub-block
    blk_RYplusXplus = thermalModel.mdl + "/Face Y+/RY+X+";
    blk_RYplusXminus = thermalModel.mdl + "/Face Y+/RY+X-";
    blk_RYplusZplus = thermalModel.mdl + "/Face Y+/RY+Z+";
    blk_RYplusZminus = thermalModel.mdl + "/Face Y+/RY+Z-";
    blk_RBYplusXplus = thermalModel.mdl + "/Face Y+/RBY+X+";
    blk_RBYplusXminus = thermalModel.mdl + "/Face Y+/RBY+X-";
    blk_RBYplusZplus = thermalModel.mdl + "/Face Y+/RBY+Z+";
    blk_RBYplusZminus = thermalModel.mdl + "/Face Y+/RBY+Z-";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...
        blk_RYplusXplus, "resistance", string(param.resistanceInterFaces(faceId, 1)),...
        blk_RYplusXminus, "resistance", string(param.resistanceInterFaces(faceId, 2)),...
        blk_RYplusZplus, "resistance", string(param.resistanceInterFaces(faceId, 5)),...
        blk_RYplusZminus, "resistance", string(param.resistanceInterFaces(faceId, 6)),...
        blk_RBYplusXplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 1)),...
        blk_RBYplusXminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 2)),...
        blk_RBYplusZplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 5)),...
        blk_RBYplusZminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 6)));

    % OuterLayer Sub-block
    blk_radiativeHeatTransfer = thermalModel.mdl + "/Face Y+/OuterLayer/Radiative Heat Transfer";
    blk_thermalMassBlanket = thermalModel.mdl + "/Face Y+/OuterLayer/Thermal Mass Blanket";


    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_radiativeHeatTransfer, "area", string(param.facesArea(faceId)),...
        blk_radiativeHeatTransfer, "rad_tr_coeff", string(param.krad(faceId)),...
        blk_thermalMassBlanket, "mass", string(param.facesBlanketMass(faceId)),...
        blk_thermalMassBlanket, "sp_heat", string(param.facesBlanketCp(faceId)));

    %% Define inputs for Face Y- block
    faceId = 4;

    % Main
    blk_RadBlanket = thermalModel.mdl + "/Face Y-/RadHeatBlanket";
    blk_Rblanket = thermalModel.mdl + "/Face Y-/R_Blanket";
    blk_thermalMass = thermalModel.mdl + "/Face Y-/Thermal Mass";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(... 
        blk_RadBlanket, "area", string(param.facesArea(faceId)),...
        blk_RadBlanket, "rad_tr_coeff", string(param.kradFace2Blanket(faceId)),...
        blk_Rblanket, "resistance", string(param.resistanceBlanket(faceId)),...
        blk_thermalMass, "mass", string(param.facesMass(faceId)),...
        blk_thermalMass, "sp_heat", string(param.facesCp(faceId)));

    % Enviromental Block
    blk_solarFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Y-/Solar Flux";
    blk_IRFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Y-/IR Flux";
    blk_AlbedoFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Y-/Albedo Flux";
    
    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_solarFlux, "VariableName", 'param.thermal.faceSolar.Yminus',...
        blk_IRFlux, "VariableName", 'param.thermal.faceIR.Yminus',...
        blk_AlbedoFlux, "VariableName",'param.thermal.faceAlbedo.Yminus');

    % Neighboor Faces Sub-block
    blk_RYminusXplus = thermalModel.mdl + "/Face Y-/RY-X+";
    blk_RYminusXminus = thermalModel.mdl + "/Face Y-/RY-X-";
    blk_RYminusZplus = thermalModel.mdl + "/Face Y-/RY-Z+";
    blk_RYminusZminus = thermalModel.mdl + "/Face Y-/RY-Z-";
    blk_RBYminusXplus = thermalModel.mdl + "/Face Y-/RBY-X+";
    blk_RBYminusXminus = thermalModel.mdl + "/Face Y-/RBY-X-";
    blk_RBYminusZplus = thermalModel.mdl + "/Face Y-/RBY-Z+";
    blk_RBYminusZminus = thermalModel.mdl + "/Face Y-/RBY-Z-";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...
        blk_RYminusXplus, "resistance", string(param.resistanceInterFaces(faceId, 1)),...
        blk_RYminusXminus, "resistance", string(param.resistanceInterFaces(faceId, 2)),...
        blk_RYminusZplus, "resistance", string(param.resistanceInterFaces(faceId, 5)),...
        blk_RYminusZminus, "resistance", string(param.resistanceInterFaces(faceId, 6)),...
        blk_RBYminusXplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 1)),...
        blk_RBYminusXminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 2)),...
        blk_RBYminusZplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 5)),...
        blk_RBYminusZminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 6)));

    % OuterLayer Sub-block
    blk_radiativeHeatTransfer = thermalModel.mdl + "/Face Y-/OuterLayer/Radiative Heat Transfer";
    blk_thermalMassBlanket = thermalModel.mdl + "/Face Y-/OuterLayer/Thermal Mass Blanket";


    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_radiativeHeatTransfer, "area", string(param.facesArea(faceId)),...
        blk_radiativeHeatTransfer, "rad_tr_coeff", string(param.krad(faceId)),...
        blk_thermalMassBlanket, "mass", string(param.facesBlanketMass(faceId)),...
        blk_thermalMassBlanket, "sp_heat", string(param.facesBlanketCp(faceId)));

    %% Define inputs for Face Z+ block
    faceId = 5;

    % Main
    blk_RadBlanket = thermalModel.mdl + "/Face Z+/RadHeatBlanket";
    blk_Rblanket = thermalModel.mdl + "/Face Z+/R_Blanket";
    blk_thermalMass = thermalModel.mdl + "/Face Z+/Thermal Mass";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(... 
        blk_RadBlanket, "area", string(param.facesArea(faceId)),...
        blk_RadBlanket, "rad_tr_coeff", string(param.kradFace2Blanket(faceId)),...
        blk_Rblanket, "resistance", string(param.resistanceBlanket(faceId)),...
        blk_thermalMass, "mass", string(param.facesMass(faceId)),...
        blk_thermalMass, "sp_heat", string(param.facesCp(faceId)));

    % Enviromental Block
    blk_solarFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Z+/Solar Flux";
    blk_IRFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Z+/IR Flux";
    blk_AlbedoFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Z+/Albedo Flux";
    
    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_solarFlux, "VariableName", 'param.thermal.faceSolar.Zplus',...
        blk_IRFlux, "VariableName", 'param.thermal.faceIR.Zplus',...
        blk_AlbedoFlux, "VariableName",'param.thermal.faceAlbedo.Zplus');

    % Neighboor Faces Sub-block
    blk_RZplusXplus = thermalModel.mdl + "/Face Z+/RZ+X+";
    blk_RZplusXminus = thermalModel.mdl + "/Face Z+/RZ+X-";
    blk_RZplusYplus = thermalModel.mdl + "/Face Z+/RZ+Y+";
    blk_RZplusYminus = thermalModel.mdl + "/Face Z+/RZ+Y-";
    blk_RBZplusXplus = thermalModel.mdl + "/Face Z+/RBZ+X+";
    blk_RBZplusXminus = thermalModel.mdl + "/Face Z+/RBZ+X-";
    blk_RBZplusYplus = thermalModel.mdl + "/Face Z+/RBZ+Y+";
    blk_RBZplusYminus = thermalModel.mdl + "/Face Z+/RBZ+Y-";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...
        blk_RZplusXplus, "resistance", string(param.resistanceInterFaces(faceId, 1)),...
        blk_RZplusXminus, "resistance", string(param.resistanceInterFaces(faceId, 2)),...
        blk_RZplusYplus, "resistance", string(param.resistanceInterFaces(faceId, 3)),...
        blk_RZplusYminus, "resistance", string(param.resistanceInterFaces(faceId, 4)),...
        blk_RBZplusXplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 1)),...
        blk_RBZplusXminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 2)),...
        blk_RBZplusYplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 3)),...
        blk_RBZplusYminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 4)));

    % OuterLayer Sub-block
    blk_radiativeHeatTransfer = thermalModel.mdl + "/Face Z+/OuterLayer/Radiative Heat Transfer";
    blk_thermalMassBlanket = thermalModel.mdl + "/Face Z+/OuterLayer/Thermal Mass Blanket";


    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_radiativeHeatTransfer, "area", string(param.facesArea(faceId)),...
        blk_radiativeHeatTransfer, "rad_tr_coeff", string(param.krad(faceId)),...
        blk_thermalMassBlanket, "mass", string(param.facesBlanketMass(faceId)),...
        blk_thermalMassBlanket, "sp_heat", string(param.facesBlanketCp(faceId)));

    %% Define inputs for Face Z- block
    faceId = 6;

    % Main
    blk_RadBlanket = thermalModel.mdl + "/Face Z-/RadHeatBlanket";
    blk_Rblanket = thermalModel.mdl + "/Face Z-/R_Blanket";
    blk_thermalMass = thermalModel.mdl + "/Face Z-/Thermal Mass";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(... 
        blk_RadBlanket, "area", string(param.facesArea(faceId)),...
        blk_RadBlanket, "rad_tr_coeff", string(param.kradFace2Blanket(faceId)),...
        blk_Rblanket, "resistance", string(param.resistanceBlanket(faceId)),...
        blk_thermalMass, "mass", string(param.facesMass(faceId)),...
        blk_thermalMass, "sp_heat", string(param.facesCp(faceId)));

    % Enviromental Block
    blk_solarFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Z-/Solar Flux";
    blk_IRFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Z-/IR Flux";
    blk_AlbedoFlux =   thermalModel.mdl + "/Thermal Loads from Enviroment Z-/Albedo Flux";
    
    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_solarFlux, "VariableName", 'param.thermal.faceSolar.Yminus',...
        blk_IRFlux, "VariableName", 'param.thermal.faceIR.Yminus',...
        blk_AlbedoFlux, "VariableName",'param.thermal.faceAlbedo.Yminus');

    % Neighboor Faces Sub-block
    blk_RZminusXplus = thermalModel.mdl + "/Face Z-/RZ-X+";
    blk_RZminusXminus = thermalModel.mdl + "/Face Z-/RZ-X-";
    blk_RZminusYplus = thermalModel.mdl + "/Face Z-/RZ-Y+";
    blk_RZminusYminus = thermalModel.mdl + "/Face Z-/RZ-Y-";
    blk_RBZminusXplus = thermalModel.mdl + "/Face Z-/RBZ-X+";
    blk_RBZminusXminus = thermalModel.mdl + "/Face Z-/RBZ-X-";
    blk_RBZminusYplus = thermalModel.mdl + "/Face Z-/RBZ-Y+";
    blk_RBZminusYminus = thermalModel.mdl + "/Face Z-/RBZ-Y-";

    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...
        blk_RZminusXplus, "resistance", string(param.resistanceInterFaces(faceId, 1)),...
        blk_RZminusXminus, "resistance", string(param.resistanceInterFaces(faceId, 2)),...
        blk_RZminusYplus, "resistance", string(param.resistanceInterFaces(faceId, 3)),...
        blk_RZminusYminus, "resistance", string(param.resistanceInterFaces(faceId, 4)),...
        blk_RBZminusXplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 1)),...
        blk_RBZminusXminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 2)),...
        blk_RBZminusYplus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 3)),...
        blk_RBZminusYminus, "resistance", string(param.resistanceInterFacesBlanket(faceId, 4)));

    % OuterLayer Sub-block
    blk_radiativeHeatTransfer = thermalModel.mdl + "/Face Z-/OuterLayer/Radiative Heat Transfer";
    blk_thermalMassBlanket = thermalModel.mdl + "/Face Z-/OuterLayer/Thermal Mass Blanket";


    thermalModel.sim.in = thermalModel.sim.in.setBlockParameter(...   
        blk_radiativeHeatTransfer, "area", string(param.facesArea(faceId)),...
        blk_radiativeHeatTransfer, "rad_tr_coeff", string(param.krad(faceId)),...
        blk_thermalMassBlanket, "mass", string(param.facesBlanketMass(faceId)),...
        blk_thermalMassBlanket, "sp_heat", string(param.facesBlanketCp(faceId)));
end
